name: deliveryman
description: "Delivery personnel app for Storify"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.0.0
  intl: ^0.18.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  google_fonts: ^6.2.1
  signature: ^6.0.0
  http_parser: ^4.1.2
  url_launcher: ^6.3.1
  flutter_phone_direct_caller: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
